spring.application.name=consumer

spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:amqp://guest:guest@rabbitmq:5672}
spring.rabbitmq.listener.simple.acknowledge-mode=MANUAL
spring.rabbitmq.listener.simple.prefetch=10

spring.data.mongodb.uri=mongodb://user:password@mongodb:27017/activity_db?authSource=admin

spring.data.mongodb.uri=mongodb://user:password@mongodb:27017/activity_db?authSource=admin