spring.application.name=consumer

spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://guest:guest@localhost:5672}
spring.rabbitmq.listener.simple.acknowledge-mode=MANUAL
spring.rabbitmq.listener.simple.prefetch=10

spring.data.mongodb.uri=${DATABASE_URL:mongodb://user:password@localhost:27017/activity_db?authSource=admin}