spring.application.name=api

server.port=${API_PORT:3000}

spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:amqp://guest:guest@rabbitmq:5672}
spring.rabbitmq.template.exchange=${RABBITMQ_EXCHANGE:activity.exchange}
spring.rabbitmq.template.routing-key=${RABBITMQ_ROUTING_KEY:activity.key}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

rate.limit.window-ms=${RATE_LIMIT_WINDOW_MS:60000}
rate.limit.max-requests=${RATE_LIMIT_MAX_REQUESTS:50}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never